dbs:
  - path: ${ZERO_REPLICA_FILE}
    min-checkpoint-page-count: ${ZERO_LITESTREAM_MIN_CHECKPOINT_PAGE_COUNT}
    max-checkpoint-page-count: ${ZERO_LITESTREAM_MAX_CHECKPOINT_PAGE_COUNT}
    watermark-table: _zero.replicationState
    watermark-column: stateVersion
    replicas:
      - type: ${ZERO_LITESTREAM_REPLICA_TYPE}
        url: ${ZERO_LITESTREAM_BACKUP_URL}
        retention: ${ZERO_LITESTREAM_SNAPSHOT_BACKUP_INTERVAL_MINUTES}m
        retention-check-interval: 1h
        sync-interval: ${ZERO_LITESTREAM_INCREMENTAL_BACKUP_INTERVAL_MINUTES}m
        access-key-id: ${ZERO_BUCKET_ACCESS_KEY_ID}
        secret-access-key: ${ZERO_BUCKET_SECRET_ACCESS_KEY}

logging:
  level: ${ZERO_LITESTREAM_LOG_LEVEL}
  type: ${ZERO_LOG_FORMAT}

addr: localhost:${LITESTREAM_PORT}
